import type { CatalogEntry } from './types';

const ui = (named: string, path: string) => ({ named, from: '@/ui', path });
const pattern = (named: string, file: string) => ({ named, from: '@/patterns', path: `src/patterns/mobile/${file}.tsx` });

export const entries: CatalogEntry[] = [
  // ── actions ───────────────────────────────────────────────────────────────
  {
    id: 'button', name: 'Button', kind: 'component', category: 'actions',
    description: 'Hauptbaustein für Aktionen und Interaktionen',
    tags: ['aktion', 'klick'],
    source: ui('Button', 'src/ui/actions/Button/Button.tsx'),
    props: [
      { name: 'children', type: 'node', required: true },
      { name: 'variant', type: 'enum', options: ['primary', 'secondary', 'ghost', 'danger'], default: 'primary' },
      { name: 'size', type: 'enum', options: ['sm', 'md', 'lg'], default: 'md' },
      { name: 'icon', type: 'node', description: 'Icon links vom Text' },
      { name: 'iconRight', type: 'node', description: 'Icon rechts vom Text' },
      { name: 'loading', type: 'boolean', default: false },
      { name: 'fullWidth', type: 'boolean', default: false },
      { name: 'disabled', type: 'boolean', default: false },
      { name: 'onClick', type: 'function' },
    ],
    snippet: `<Button variant="primary" icon={<Plus size={16} />}>\n  Erstellen\n</Button>`,
  },
  {
    id: 'icon-button', name: 'IconButton', kind: 'component', category: 'actions',
    description: 'Kompakter Button nur mit Icon',
    tags: ['aktion', 'icon'],
    source: ui('IconButton', 'src/ui/actions/IconButton/IconButton.tsx'),
    props: [
      { name: 'children', type: 'node', required: true, description: 'Das Icon' },
      { name: 'variant', type: 'enum', options: ['ghost', 'surface'], default: 'ghost' },
      { name: 'size', type: 'number', default: 40, description: 'Kantenlänge in Pixeln' },
      { name: 'onClick', type: 'function' },
    ],
    snippet: `<IconButton variant="surface" onClick={onBack}>\n  <ArrowLeft size={20} />\n</IconButton>`,
  },
  {
    id: 'tabs', name: 'Tabs', kind: 'component', category: 'actions',
    description: 'Umschalter zwischen Ansichten',
    tags: ['navigation', 'umschalten'],
    source: ui('Tabs', 'src/ui/actions/Tabs/Tabs.tsx'),
    props: [
      { name: 'items', type: 'array', required: true, description: '{ id, label }[]' },
      { name: 'active', type: 'string', required: true },
      { name: 'onChange', type: 'function', required: true, description: '(id: string) => void' },
    ],
    snippet: `<Tabs\n  items={[{ id: 'a', label: 'Übersicht' }, { id: 'b', label: 'Details' }]}\n  active={active}\n  onChange={setActive}\n/>`,
  },
  {
    id: 'chips', name: 'Chips', kind: 'component', category: 'actions',
    description: 'Auswahl- und Filter-Chips mit Tags',
    tags: ['filter', 'tag', 'auswahl'],
    source: ui('Chip', 'src/ui/actions/Chips/Chips.tsx'),
    props: [
      { name: 'label', type: 'string', required: true },
      { name: 'active', type: 'boolean', default: false },
      { name: 'onToggle', type: 'function' },
      { name: 'onRemove', type: 'function', description: 'Zeigt ein Löschkreuz an' },
      { name: 'icon', type: 'node' },
    ],
    snippet: `<ChipGroup>\n  <Chip label="Aktiv" active onToggle={toggle} />\n  <Chip label="Wartend" onToggle={toggle} />\n</ChipGroup>`,
  },
  {
    id: 'dropdown', name: 'Dropdown', kind: 'component', category: 'actions',
    description: 'Auswahlfeld mit aufklappbarer Liste',
    tags: ['auswahl', 'formular', 'menü'],
    source: ui('Dropdown', 'src/ui/actions/Dropdown/Dropdown.tsx'),
    props: [
      { name: 'options', type: 'array', required: true, description: '{ id, label, icon? }[]' },
      { name: 'onChange', type: 'function', required: true, description: '(id: string) => void' },
      { name: 'value', type: 'string' },
      { name: 'placeholder', type: 'string', default: 'Auswählen…' },
      { name: 'label', type: 'string' },
    ],
    snippet: `<Dropdown\n  label="Priorität"\n  options={[{ id: 'high', label: 'Hoch' }, { id: 'low', label: 'Niedrig' }]}\n  value={value}\n  onChange={setValue}\n/>`,
  },

  // ── data-display ──────────────────────────────────────────────────────────
  {
    id: 'card', name: 'Card', kind: 'component', category: 'data-display',
    description: 'Inhaltsfläche mit verschiedenen Stilen',
    tags: ['fläche', 'container'],
    source: ui('Card', 'src/ui/data-display/Card/Card.tsx'),
    props: [
      { name: 'children', type: 'node', required: true },
      { name: 'variant', type: 'enum', options: ['default', 'outlined', 'elevated', 'accent'], default: 'default' },
      { name: 'padding', type: 'enum', options: ['sm', 'md', 'lg'], default: 'md' },
      { name: 'onClick', type: 'function', description: 'Macht die Karte klickbar' },
    ],
    snippet: `<Card variant="elevated" padding="lg">\n  Inhalt\n</Card>`,
  },
  {
    id: 'badge', name: 'Badge', kind: 'component', category: 'data-display',
    description: 'Kleine Status- oder Kategoriemarkierung',
    tags: ['status', 'kennzeichnung'],
    source: ui('Badge', 'src/ui/data-display/Badge/Badge.tsx'),
    props: [
      { name: 'children', type: 'node', required: true },
      { name: 'color', type: 'enum', options: ['accent', 'success', 'warning', 'error', 'neutral'], default: 'accent' },
    ],
    snippet: `<Badge color="success">Aktiv</Badge>`,
  },
  {
    id: 'divider', name: 'Divider', kind: 'component', category: 'data-display',
    description: 'Visueller Trenner zwischen Bereichen',
    tags: ['trenner'],
    source: ui('Divider', 'src/ui/data-display/Divider/Divider.tsx'),
    props: [
      { name: 'spacing', type: 'number', default: 16, description: 'Abstand oben und unten in Pixeln' },
      { name: 'label', type: 'string', description: 'Text mittig auf der Linie' },
    ],
    snippet: `<Divider label="Oder" />`,
  },
  {
    id: 'list-item', name: 'ListItem', kind: 'component', category: 'data-display',
    description: 'Listenzeile mit Icon, Text und Aktion',
    tags: ['liste', 'zeile', 'navigation'],
    source: ui('ListItem', 'src/ui/data-display/ListItem/ListItem.tsx'),
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'subtitle', type: 'string' },
      { name: 'leading', type: 'node', description: 'Icon links in getönter Fläche' },
      { name: 'trailing', type: 'node' },
      { name: 'showArrow', type: 'boolean', default: true },
      { name: 'onClick', type: 'function' },
    ],
    snippet: `<ListItem\n  title="Auftrag #1042"\n  subtitle="Welle Ø25"\n  leading={<Package size={18} />}\n  onClick={open}\n/>`,
  },
  {
    id: 'avatar', name: 'Avatar', kind: 'component', category: 'data-display',
    description: 'Profilbild mit Initialen, Farbe und Status',
    tags: ['profil', 'benutzer', 'bild'],
    source: ui('Avatar', 'src/ui/data-display/Avatar/Avatar.tsx'),
    props: [
      { name: 'name', type: 'string', required: true, description: 'Bestimmt Initialen und Farbe' },
      { name: 'src', type: 'string', description: 'Bild-URL statt Initialen' },
      { name: 'size', type: 'enum', options: ['sm', 'md', 'lg'], default: 'md' },
      { name: 'status', type: 'enum', options: ['online', 'offline', 'busy'] },
    ],
    snippet: `<Avatar name="Max Konrad" status="online" />`,
  },

  // ── inputs ────────────────────────────────────────────────────────────────
  {
    id: 'input', name: 'Input', kind: 'component', category: 'inputs',
    description: 'Texteingabefeld mit Label und Fehlermeldung',
    tags: ['formular', 'eingabe'],
    source: ui('Input', 'src/ui/inputs/Input/Input.tsx'),
    props: [
      { name: 'label', type: 'string' },
      { name: 'error', type: 'string', description: 'Färbt den Rahmen und zeigt den Text darunter' },
      { name: 'hint', type: 'string' },
      { name: 'placeholder', type: 'string' },
      { name: 'value', type: 'string' },
      { name: 'onChange', type: 'function' },
    ],
    snippet: `<Input label="Bezeichnung" placeholder="z.B. Welle Ø25" hint="Pflichtfeld" />`,
  },
  {
    id: 'search-field', name: 'SearchField', kind: 'component', category: 'inputs',
    description: 'Suchfeld mit Icon und Löschen-Funktion',
    tags: ['suche', 'filter'],
    source: ui('SearchField', 'src/ui/inputs/SearchField/SearchField.tsx'),
    props: [
      { name: 'value', type: 'string', required: true },
      { name: 'onChange', type: 'function', required: true, description: '(val: string) => void' },
      { name: 'placeholder', type: 'string', default: 'Suchen…' },
    ],
    snippet: `<SearchField value={search} onChange={setSearch} />`,
  },
  {
    id: 'toggle', name: 'Toggle', kind: 'component', category: 'inputs',
    description: 'Ein/Aus-Schalter für Einstellungen',
    tags: ['schalter', 'ja/nein'],
    source: ui('Toggle', 'src/ui/inputs/Toggle/Toggle.tsx'),
    props: [
      { name: 'checked', type: 'boolean', required: true },
      { name: 'onChange', type: 'function', required: true, description: '(val: boolean) => void' },
      { name: 'label', type: 'string' },
      { name: 'disabled', type: 'boolean', default: false },
    ],
    snippet: `<Toggle checked={enabled} onChange={setEnabled} label="Benachrichtigungen" />`,
  },

  // ── feedback ──────────────────────────────────────────────────────────────
  {
    id: 'loading-state', name: 'LoadingState', kind: 'component', category: 'feedback',
    description: 'Ladeanzeige mit Spinner und Text',
    tags: ['laden', 'spinner', 'warten'],
    source: ui('LoadingState', 'src/ui/feedback/LoadingState/LoadingState.tsx'),
    props: [{ name: 'label', type: 'string', default: 'Laden…' }],
    snippet: `<LoadingState label="Aufträge werden geladen…" />`,
  },
  {
    id: 'error-state', name: 'ErrorState', kind: 'component', category: 'feedback',
    description: 'Fehlermeldung mit Icon und Text',
    tags: ['fehler', 'meldung'],
    source: ui('ErrorState', 'src/ui/feedback/ErrorState/ErrorState.tsx'),
    props: [{ name: 'message', type: 'string', default: 'Etwas ist schiefgelaufen.' }],
    snippet: `<ErrorState message="Verbindung fehlgeschlagen." />`,
  },
  {
    id: 'empty-state', name: 'EmptyState', kind: 'component', category: 'feedback',
    description: 'Platzhalter wenn keine Inhalte vorhanden sind',
    tags: ['leer', 'platzhalter'],
    source: ui('EmptyState', 'src/ui/feedback/EmptyState/EmptyState.tsx'),
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'description', type: 'string' },
      { name: 'icon', type: 'node' },
      { name: 'action', type: 'node', description: 'z.B. ein Button' },
    ],
    snippet: `<EmptyState\n  icon={<Search size={36} />}\n  title="Nichts gefunden"\n  description="Keine Ergebnisse für diesen Filter."\n/>`,
  },
  {
    id: 'sheet', name: 'Sheet', kind: 'component', category: 'feedback',
    description: 'Einschiebbares Overlay als Sidebar oder von unten',
    tags: ['overlay', 'sidebar', 'navigation'],
    source: ui('Sheet', 'src/ui/feedback/Sheet/Sheet.tsx'),
    props: [
      { name: 'open', type: 'boolean', required: true },
      { name: 'onClose', type: 'function', required: true },
      { name: 'children', type: 'node', required: true },
      { name: 'title', type: 'string' },
      { name: 'side', type: 'enum', options: ['left', 'bottom'], default: 'left' },
    ],
    snippet: `<Sheet open={open} onClose={close} title="Filter" side="bottom">\n  Inhalt\n</Sheet>`,
  },
  {
    id: 'progress', name: 'Progress', kind: 'component', category: 'feedback',
    description: 'Fortschrittsbalken mit Farben und Label',
    tags: ['fortschritt', 'status', 'balken'],
    source: ui('Progress', 'src/ui/feedback/Progress/Progress.tsx'),
    props: [
      { name: 'value', type: 'number', required: true },
      { name: 'max', type: 'number', default: 100 },
      { name: 'size', type: 'enum', options: ['sm', 'md'], default: 'md' },
      { name: 'color', type: 'enum', options: ['accent', 'success', 'warning', 'error'], default: 'accent' },
      { name: 'label', type: 'string' },
    ],
    snippet: `<Progress value={38} max={47} label="Erledigt" color="success" />`,
  },
  {
    id: 'skeleton', name: 'Skeleton', kind: 'component', category: 'feedback',
    description: 'Shimmer-Platzhalter während Inhalte laden',
    tags: ['laden', 'platzhalter', 'shimmer'],
    source: ui('Skeleton', 'src/ui/feedback/Skeleton/Skeleton.tsx'),
    props: [
      { name: 'variant', type: 'enum', options: ['text', 'circle', 'rect'], default: 'text' },
      { name: 'width', type: 'string', description: 'CSS-Breite, z.B. "60%"' },
      { name: 'height', type: 'string' },
      { name: 'radius', type: 'string' },
    ],
    snippet: `<Skeleton variant="text" width="60%" />\n<SkeletonCard />`,
  },
  {
    id: 'modal', name: 'Modal', kind: 'component', category: 'feedback',
    description: 'Zentrierter Dialog für Bestätigungen und Hinweise',
    tags: ['dialog', 'overlay', 'bestätigung'],
    source: ui('Modal', 'src/ui/feedback/Modal/Modal.tsx'),
    props: [
      { name: 'open', type: 'boolean', required: true },
      { name: 'onClose', type: 'function', required: true },
      { name: 'children', type: 'node', required: true },
      { name: 'title', type: 'string' },
      { name: 'actions', type: 'node', description: 'Buttons im Fuß des Dialogs' },
    ],
    snippet: `<Modal\n  open={open}\n  onClose={close}\n  title="Löschen?"\n  actions={<Button variant="danger">Löschen</Button>}\n>\n  Das lässt sich nicht rückgängig machen.\n</Modal>`,
  },
  {
    id: 'toast', name: 'Toast', kind: 'component', category: 'feedback',
    description: 'Kurze Rückmeldung als temporäre Benachrichtigung',
    tags: ['benachrichtigung', 'meldung', 'feedback'],
    source: ui('ToastProvider', 'src/ui/feedback/Toast/Toast.tsx'),
    props: [
      { name: 'message', type: 'string', required: true, description: 'Erstes Argument von toast()' },
      { name: 'type', type: 'enum', options: ['success', 'error', 'info', 'warning'], default: 'info' },
    ],
    snippet: `// App einmalig umschließen:\n<ToastProvider>{children}</ToastProvider>\n\n// dann überall:\nconst { toast } = useToast();\ntoast('Gespeichert', 'success');`,
  },

  // ── composite (Patterns) ──────────────────────────────────────────────────
  {
    id: 'card-actions', name: 'Card + Aktionen', kind: 'pattern', category: 'composite',
    description: 'Karte mit Titel, Badge und Aktionsleiste',
    tags: ['karte', 'aktion', 'bearbeiten'],
    source: pattern('CardActions', 'CardActions'),
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'subtitle', type: 'string' },
      { name: 'badge', type: 'object', description: '{ label, color }' },
      { name: 'onEdit', type: 'function' },
      { name: 'onDelete', type: 'function' },
    ],
    snippet: `<CardActions\n  title="Auftrag #1042"\n  subtitle="Welle Ø25 — 120 Stück"\n  badge={{ label: 'Aktiv', color: 'success' }}\n  onEdit={edit}\n/>`,
  },
  {
    id: 'list-filter-search', name: 'Liste + Suche', kind: 'pattern', category: 'composite',
    description: 'Durchsuchbare Liste mit Leerzustand',
    tags: ['liste', 'suche', 'filter'],
    source: pattern('ListFilterSearch', 'ListFilterSearch'),
    props: [
      { name: 'items', type: 'array', required: true, description: '{ id, title, subtitle?, badge? }[]' },
      { name: 'onSelect', type: 'function' },
    ],
    snippet: `<ListFilterSearch items={items} onSelect={open} />`,
  },
  {
    id: 'form-section', name: 'Formularbereich', kind: 'pattern', category: 'composite',
    description: 'Gruppierter Formularabschnitt mit Titel',
    tags: ['formular', 'gruppe'],
    source: pattern('FormSection', 'FormSection'),
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'description', type: 'string' },
      { name: 'children', type: 'node', required: true },
    ],
    snippet: `<FormSection title="Stammdaten" description="Pflichtangaben">\n  <Input label="Bezeichnung" />\n</FormSection>`,
  },
  {
    id: 'detail-header', name: 'Detailkopf', kind: 'pattern', category: 'composite',
    description: 'Kopfzeile mit Zurück-Button, Titel und Aktionen',
    tags: ['kopf', 'zurück', 'navigation'],
    source: pattern('DetailHeader', 'DetailHeader'),
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'subtitle', type: 'string' },
      { name: 'onBack', type: 'function' },
      { name: 'actions', type: 'node' },
    ],
    snippet: `<DetailHeader title="Auftrag #1042" subtitle="Welle Ø25" onBack={goBack} />`,
  },
  {
    id: 'action-panel', name: 'Aktionsleiste', kind: 'pattern', category: 'composite',
    description: 'Am unteren Rand fixierte Aktionsleiste',
    tags: ['aktion', 'fixiert', 'fuß'],
    source: pattern('ActionPanel', 'ActionPanel'),
    props: [{ name: 'children', type: 'node', required: true }],
    snippet: `<ActionPanel>\n  <Button fullWidth>Speichern</Button>\n</ActionPanel>`,
  },
  {
    id: 'info-panel', name: 'Info-Panel', kind: 'pattern', category: 'composite',
    description: 'Kennzahl mit Icon, Wert und optionalem Badge',
    tags: ['kennzahl', 'info', 'panel'],
    source: pattern('InfoPanel', 'InfoPanel'),
    props: [
      { name: 'icon', type: 'node', required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'value', type: 'string', required: true },
      { name: 'subtitle', type: 'string' },
      { name: 'badge', type: 'object', description: '{ label, color }' },
      { name: 'variant', type: 'enum', options: ['default', 'accent'], default: 'default' },
    ],
    snippet: `<InfoPanel icon={<Clock size={18} />} title="Laufzeit" value="4,2 h" variant="accent" />`,
  },
  {
    id: 'stat-cards', name: 'Statistik-Cards', kind: 'pattern', category: 'composite',
    description: 'Kompaktes Statistik-Grid mit Trends',
    tags: ['statistik', 'kennzahl', 'grid'],
    source: pattern('StatCards', 'StatCards'),
    props: [
      { name: 'items', type: 'array', required: true, description: '{ label, value, trend?, icon? }[]' },
      { name: 'columns', type: 'enum', options: ['2', '3'], default: 2 },
    ],
    snippet: `<StatCards columns={3} items={[\n  { label: 'Heute', value: '12' },\n  { label: 'Woche', value: '47' },\n]} />`,
  },
  {
    id: 'avatar-group', name: 'Avatar-Gruppe', kind: 'pattern', category: 'composite',
    description: 'Überlappende Avatare mit Überlauf-Zähler',
    tags: ['avatar', 'gruppe', 'team'],
    source: pattern('AvatarGroup', 'AvatarGroup'),
    props: [
      { name: 'users', type: 'array', required: true, description: '{ name, status? }[]' },
      { name: 'max', type: 'number', default: 4, description: 'Ab hier wird gezählt statt gezeigt' },
      { name: 'size', type: 'enum', options: ['sm', 'md'], default: 'md' },
    ],
    snippet: `<AvatarGroup users={[{ name: 'Max K.' }, { name: 'Lea B.' }]} max={4} />`,
  },
  {
    id: 'notification-list', name: 'Benachrichtigungen', kind: 'pattern', category: 'composite',
    description: 'Liste mit Gelesen-Status und Zeitangabe',
    tags: ['benachrichtigung', 'liste', 'gelesen'],
    source: pattern('NotificationList', 'NotificationList'),
    props: [
      { name: 'items', type: 'array', required: true, description: '{ id, title, message, time, read, avatar? }[]' },
      { name: 'onTap', type: 'function' },
    ],
    snippet: `<NotificationList items={items} onTap={open} />`,
  },
];
